export enum Genre {
	all = "all",
	action = "action",
	thriller = "thriller",
	drama = "drama",
	comedy = "comedy",
	romantic = "romantic",
	horror = "horror",
	fantastic = "fantastic",
	adventurous = "adventurous",
	historical = "historical",
	mistery = "mistery",
	fantasy = "fantasy",
	military = "military",
	western = "western",
	russian = "russian",
	biographical = "biographical",
	criminal = "criminal",
	documentary = "documentary",
	sporty = "sporty",
	indian = "indian",
}

export const genreNamesMap = new Map<string, string>([
	["all", "Всички"],
	["action", "Екшън"],
	["thriller", "Трилър"],
	["drama", "Драма"],
	["comedy", "Комедия"],
	["romantic", "Романтичен"],
	["horror", "Ужаси"],
	["fantastic", "Фантастика"],
	["adventurous", "Приключенски"],
	["historical", "Исторически"],
	["mistery", "Мистерия"],
	["fantasy", "Фентъзи"],
	["military", "Военен"],
	["western", "Уестърн"],
	["russian", "Руски"],
	["biographical", "Биографичен"],
	["criminal", "Криминален"],
	["documentary", "Документален"],
	["sporty", "Спортен"],
	["indian", "Индийски"],
]);
